// Generated by CoffeeScript 1.10.0
(function() {
  var fs, system;

  system = require('system');

  fs = require('fs');

  exports.init = function() {
    var environment;
    environment = system.env.NODE_ENV || 'default';
    return JSON.parse(fs.read("./config/" + environment + ".json", 'utf8'));
  };

}).call(this);
