// Generated by CoffeeScript 1.10.0
(function() {
  var capture, log, system, timeStamp;

  system = require('system');

  timeStamp = (new Date).getTime();

  log = function(message) {
    if (!casper.cli.get('quiet')) {
      return casper.test.comment(message);
    }
  };

  capture = function(name) {
    var filePath, step;
    step = casper.status().step;
    filePath = "logs/capture/" + timeStamp + "_" + step + "_" + name + ".png";
    if (!casper.cli.get('no-capture')) {
      return casper.capture(filePath);
    }
  };

  exports.init = function(timeout) {
    casper.options.onWaitTimeout = function(timeout) {
      this.test.error("Timed out error in " + timeout + "ms. Now taking capture...");
      capture('on_wait_timeout');
      return this.die("Error onWaitTimeout.", 1);
    };
    return exports;
  };

  exports.visitPage = function(self) {
    var message;
    message = "[Visit page] title: \"" + (self.getTitle()) + "\", url: \"" + (self.getCurrentUrl()) + "\"";
    return log(message);
  };

  exports.log = function(message) {
    return log(message);
  };

  exports.capture = function(name) {
    return capture(name);
  };

}).call(this);
