// Generated by CoffeeScript 1.10.0
(function() {
  var config, logger;

  config = require('../lib/config').init();

  logger = require('../lib/logger').init();

  casper.userAgent(config['user_agent']['nexus5_chrome']);

  casper.start('http://example.com/', function() {
    return this.waitForSelector('h1', function() {
      logger.visitPage(this);
      logger.capture('page');
      this.test.assertTitle('Example Domain', 'example.com has expected title.');
      return this.test.assertTextExists('Example Domain', 'example.com has expected text.');
    });
  }).run(function() {
    this.test.done();
    return this.test.renderResults(true, 0, 'coverage/test-result.xml');
  });

}).call(this);
